// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// FormsUIClient is the client API for FormsUI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FormsUIClient interface {
	// ListDocumentSpecs returns a list of Document that can be started through the UI.
	ListDocumentSpecs(ctx context.Context, in *ListDocumentSpecsRequest, opts ...grpc.CallOption) (FormsUI_ListDocumentSpecsClient, error)
	// IsReadOnly returns true if the UI is readonly.
	IsReadOnly(ctx context.Context, in *IsReadOnlyRequest, opts ...grpc.CallOption) (*IsReadOnlyResponse, error)
}

type formsUIClient struct {
	cc grpc.ClientConnInterface
}

func NewFormsUIClient(cc grpc.ClientConnInterface) FormsUIClient {
	return &formsUIClient{cc}
}

func (c *formsUIClient) ListDocumentSpecs(ctx context.Context, in *ListDocumentSpecsRequest, opts ...grpc.CallOption) (FormsUI_ListDocumentSpecsClient, error) {
	stream, err := c.cc.NewStream(ctx, &FormsUI_ServiceDesc.Streams[0], "/v1.FormsUI/ListDocumentSpecs", opts...)
	if err != nil {
		return nil, err
	}
	x := &formsUIListDocumentSpecsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type FormsUI_ListDocumentSpecsClient interface {
	Recv() (*ListDocumentSpecsResponse, error)
	grpc.ClientStream
}

type formsUIListDocumentSpecsClient struct {
	grpc.ClientStream
}

func (x *formsUIListDocumentSpecsClient) Recv() (*ListDocumentSpecsResponse, error) {
	m := new(ListDocumentSpecsResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *formsUIClient) IsReadOnly(ctx context.Context, in *IsReadOnlyRequest, opts ...grpc.CallOption) (*IsReadOnlyResponse, error) {
	out := new(IsReadOnlyResponse)
	err := c.cc.Invoke(ctx, "/v1.FormsUI/IsReadOnly", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FormsUIServer is the server API for FormsUI service.
// All implementations must embed UnimplementedFormsUIServer
// for forward compatibility
type FormsUIServer interface {
	// ListDocumentSpecs returns a list of Document that can be started through the UI.
	ListDocumentSpecs(*ListDocumentSpecsRequest, FormsUI_ListDocumentSpecsServer) error
	// IsReadOnly returns true if the UI is readonly.
	IsReadOnly(context.Context, *IsReadOnlyRequest) (*IsReadOnlyResponse, error)
	mustEmbedUnimplementedFormsUIServer()
}

// UnimplementedFormsUIServer must be embedded to have forward compatible implementations.
type UnimplementedFormsUIServer struct {
}

func (UnimplementedFormsUIServer) ListDocumentSpecs(*ListDocumentSpecsRequest, FormsUI_ListDocumentSpecsServer) error {
	return status.Errorf(codes.Unimplemented, "method ListDocumentSpecs not implemented")
}
func (UnimplementedFormsUIServer) IsReadOnly(context.Context, *IsReadOnlyRequest) (*IsReadOnlyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IsReadOnly not implemented")
}
func (UnimplementedFormsUIServer) mustEmbedUnimplementedFormsUIServer() {}

// UnsafeFormsUIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FormsUIServer will
// result in compilation errors.
type UnsafeFormsUIServer interface {
	mustEmbedUnimplementedFormsUIServer()
}

func RegisterFormsUIServer(s grpc.ServiceRegistrar, srv FormsUIServer) {
	s.RegisterService(&FormsUI_ServiceDesc, srv)
}

func _FormsUI_ListDocumentSpecs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ListDocumentSpecsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(FormsUIServer).ListDocumentSpecs(m, &formsUIListDocumentSpecsServer{stream})
}

type FormsUI_ListDocumentSpecsServer interface {
	Send(*ListDocumentSpecsResponse) error
	grpc.ServerStream
}

type formsUIListDocumentSpecsServer struct {
	grpc.ServerStream
}

func (x *formsUIListDocumentSpecsServer) Send(m *ListDocumentSpecsResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _FormsUI_IsReadOnly_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IsReadOnlyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FormsUIServer).IsReadOnly(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.FormsUI/IsReadOnly",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FormsUIServer).IsReadOnly(ctx, req.(*IsReadOnlyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// FormsUI_ServiceDesc is the grpc.ServiceDesc for FormsUI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FormsUI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "v1.FormsUI",
	HandlerType: (*FormsUIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "IsReadOnly",
			Handler:    _FormsUI_IsReadOnly_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ListDocumentSpecs",
			Handler:       _FormsUI_ListDocumentSpecs_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "forms-ui.proto",
}
