// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// FormsServiceClient is the client API for FormsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FormsServiceClient interface {
	// StartLocalDocument starts a Form Document on the Bhojpur.NET Platform directly.
	// The incoming requests are expected in the following order:
	//   1. metadata
	//   2. all bytes constituting the reports/config.yaml
	//   3. all bytes constituting the Document YAML that will be executed (that the config.yaml points to)
	//   4. all bytes constituting the gzipped Bhojpur.NET Platform application tar stream
	//   5. the Bhojpur.NET Platform application tar stream done marker
	StartLocalDocument(ctx context.Context, opts ...grpc.CallOption) (FormsService_StartLocalDocumentClient, error)
	// StartFromPreviousDocument starts a new Document based on a previous one.
	// If the previous Document does not have the can-replay condition set this call will result in an error.
	StartFromPreviousDocument(ctx context.Context, in *StartFromPreviousDocumentRequest, opts ...grpc.CallOption) (*StartDocumentResponse, error)
	// StartDocumentRequest starts a new Document based on its specification.
	StartDocument(ctx context.Context, in *StartDocumentRequest, opts ...grpc.CallOption) (*StartDocumentResponse, error)
	// Searches for Document known to this instance
	ListDocument(ctx context.Context, in *ListDocumentRequest, opts ...grpc.CallOption) (*ListDocumentResponse, error)
	// Subscribe listens to new Document updates
	Subscribe(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (FormsService_SubscribeClient, error)
	// GetDocument retrieves details of a single Document
	GetDocument(ctx context.Context, in *GetDocumentRequest, opts ...grpc.CallOption) (*GetDocumentResponse, error)
	// Listen listens to Document updates and log output of a running Document
	Listen(ctx context.Context, in *ListenRequest, opts ...grpc.CallOption) (FormsService_ListenClient, error)
	// StopDocument stops a currently running Document
	StopDocument(ctx context.Context, in *StopDocumentRequest, opts ...grpc.CallOption) (*StopDocumentResponse, error)
}

type formsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFormsServiceClient(cc grpc.ClientConnInterface) FormsServiceClient {
	return &formsServiceClient{cc}
}

func (c *formsServiceClient) StartLocalDocument(ctx context.Context, opts ...grpc.CallOption) (FormsService_StartLocalDocumentClient, error) {
	stream, err := c.cc.NewStream(ctx, &FormsService_ServiceDesc.Streams[0], "/v1.FormsService/StartLocalDocument", opts...)
	if err != nil {
		return nil, err
	}
	x := &formsServiceStartLocalDocumentClient{stream}
	return x, nil
}

type FormsService_StartLocalDocumentClient interface {
	Send(*StartLocalDocumentRequest) error
	CloseAndRecv() (*StartDocumentResponse, error)
	grpc.ClientStream
}

type formsServiceStartLocalDocumentClient struct {
	grpc.ClientStream
}

func (x *formsServiceStartLocalDocumentClient) Send(m *StartLocalDocumentRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *formsServiceStartLocalDocumentClient) CloseAndRecv() (*StartDocumentResponse, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(StartDocumentResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *formsServiceClient) StartFromPreviousDocument(ctx context.Context, in *StartFromPreviousDocumentRequest, opts ...grpc.CallOption) (*StartDocumentResponse, error) {
	out := new(StartDocumentResponse)
	err := c.cc.Invoke(ctx, "/v1.FormsService/StartFromPreviousDocument", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *formsServiceClient) StartDocument(ctx context.Context, in *StartDocumentRequest, opts ...grpc.CallOption) (*StartDocumentResponse, error) {
	out := new(StartDocumentResponse)
	err := c.cc.Invoke(ctx, "/v1.FormsService/StartDocument", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *formsServiceClient) ListDocument(ctx context.Context, in *ListDocumentRequest, opts ...grpc.CallOption) (*ListDocumentResponse, error) {
	out := new(ListDocumentResponse)
	err := c.cc.Invoke(ctx, "/v1.FormsService/ListDocument", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *formsServiceClient) Subscribe(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (FormsService_SubscribeClient, error) {
	stream, err := c.cc.NewStream(ctx, &FormsService_ServiceDesc.Streams[1], "/v1.FormsService/Subscribe", opts...)
	if err != nil {
		return nil, err
	}
	x := &formsServiceSubscribeClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type FormsService_SubscribeClient interface {
	Recv() (*SubscribeResponse, error)
	grpc.ClientStream
}

type formsServiceSubscribeClient struct {
	grpc.ClientStream
}

func (x *formsServiceSubscribeClient) Recv() (*SubscribeResponse, error) {
	m := new(SubscribeResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *formsServiceClient) GetDocument(ctx context.Context, in *GetDocumentRequest, opts ...grpc.CallOption) (*GetDocumentResponse, error) {
	out := new(GetDocumentResponse)
	err := c.cc.Invoke(ctx, "/v1.FormsService/GetDocument", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *formsServiceClient) Listen(ctx context.Context, in *ListenRequest, opts ...grpc.CallOption) (FormsService_ListenClient, error) {
	stream, err := c.cc.NewStream(ctx, &FormsService_ServiceDesc.Streams[2], "/v1.FormsService/Listen", opts...)
	if err != nil {
		return nil, err
	}
	x := &formsServiceListenClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type FormsService_ListenClient interface {
	Recv() (*ListenResponse, error)
	grpc.ClientStream
}

type formsServiceListenClient struct {
	grpc.ClientStream
}

func (x *formsServiceListenClient) Recv() (*ListenResponse, error) {
	m := new(ListenResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *formsServiceClient) StopDocument(ctx context.Context, in *StopDocumentRequest, opts ...grpc.CallOption) (*StopDocumentResponse, error) {
	out := new(StopDocumentResponse)
	err := c.cc.Invoke(ctx, "/v1.FormsService/StopDocument", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FormsServiceServer is the server API for FormsService service.
// All implementations must embed UnimplementedFormsServiceServer
// for forward compatibility
type FormsServiceServer interface {
	// StartLocalDocument starts a Form Document on the Bhojpur.NET Platform directly.
	// The incoming requests are expected in the following order:
	//   1. metadata
	//   2. all bytes constituting the reports/config.yaml
	//   3. all bytes constituting the Document YAML that will be executed (that the config.yaml points to)
	//   4. all bytes constituting the gzipped Bhojpur.NET Platform application tar stream
	//   5. the Bhojpur.NET Platform application tar stream done marker
	StartLocalDocument(FormsService_StartLocalDocumentServer) error
	// StartFromPreviousDocument starts a new Document based on a previous one.
	// If the previous Document does not have the can-replay condition set this call will result in an error.
	StartFromPreviousDocument(context.Context, *StartFromPreviousDocumentRequest) (*StartDocumentResponse, error)
	// StartDocumentRequest starts a new Document based on its specification.
	StartDocument(context.Context, *StartDocumentRequest) (*StartDocumentResponse, error)
	// Searches for Document known to this instance
	ListDocument(context.Context, *ListDocumentRequest) (*ListDocumentResponse, error)
	// Subscribe listens to new Document updates
	Subscribe(*SubscribeRequest, FormsService_SubscribeServer) error
	// GetDocument retrieves details of a single Document
	GetDocument(context.Context, *GetDocumentRequest) (*GetDocumentResponse, error)
	// Listen listens to Document updates and log output of a running Document
	Listen(*ListenRequest, FormsService_ListenServer) error
	// StopDocument stops a currently running Document
	StopDocument(context.Context, *StopDocumentRequest) (*StopDocumentResponse, error)
	mustEmbedUnimplementedFormsServiceServer()
}

// UnimplementedFormsServiceServer must be embedded to have forward compatible implementations.
type UnimplementedFormsServiceServer struct {
}

func (UnimplementedFormsServiceServer) StartLocalDocument(FormsService_StartLocalDocumentServer) error {
	return status.Errorf(codes.Unimplemented, "method StartLocalDocument not implemented")
}
func (UnimplementedFormsServiceServer) StartFromPreviousDocument(context.Context, *StartFromPreviousDocumentRequest) (*StartDocumentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartFromPreviousDocument not implemented")
}
func (UnimplementedFormsServiceServer) StartDocument(context.Context, *StartDocumentRequest) (*StartDocumentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartDocument not implemented")
}
func (UnimplementedFormsServiceServer) ListDocument(context.Context, *ListDocumentRequest) (*ListDocumentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListDocument not implemented")
}
func (UnimplementedFormsServiceServer) Subscribe(*SubscribeRequest, FormsService_SubscribeServer) error {
	return status.Errorf(codes.Unimplemented, "method Subscribe not implemented")
}
func (UnimplementedFormsServiceServer) GetDocument(context.Context, *GetDocumentRequest) (*GetDocumentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDocument not implemented")
}
func (UnimplementedFormsServiceServer) Listen(*ListenRequest, FormsService_ListenServer) error {
	return status.Errorf(codes.Unimplemented, "method Listen not implemented")
}
func (UnimplementedFormsServiceServer) StopDocument(context.Context, *StopDocumentRequest) (*StopDocumentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StopDocument not implemented")
}
func (UnimplementedFormsServiceServer) mustEmbedUnimplementedFormsServiceServer() {}

// UnsafeFormsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FormsServiceServer will
// result in compilation errors.
type UnsafeFormsServiceServer interface {
	mustEmbedUnimplementedFormsServiceServer()
}

func RegisterFormsServiceServer(s grpc.ServiceRegistrar, srv FormsServiceServer) {
	s.RegisterService(&FormsService_ServiceDesc, srv)
}

func _FormsService_StartLocalDocument_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(FormsServiceServer).StartLocalDocument(&formsServiceStartLocalDocumentServer{stream})
}

type FormsService_StartLocalDocumentServer interface {
	SendAndClose(*StartDocumentResponse) error
	Recv() (*StartLocalDocumentRequest, error)
	grpc.ServerStream
}

type formsServiceStartLocalDocumentServer struct {
	grpc.ServerStream
}

func (x *formsServiceStartLocalDocumentServer) SendAndClose(m *StartDocumentResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *formsServiceStartLocalDocumentServer) Recv() (*StartLocalDocumentRequest, error) {
	m := new(StartLocalDocumentRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _FormsService_StartFromPreviousDocument_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartFromPreviousDocumentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FormsServiceServer).StartFromPreviousDocument(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.FormsService/StartFromPreviousDocument",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FormsServiceServer).StartFromPreviousDocument(ctx, req.(*StartFromPreviousDocumentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FormsService_StartDocument_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartDocumentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FormsServiceServer).StartDocument(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.FormsService/StartDocument",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FormsServiceServer).StartDocument(ctx, req.(*StartDocumentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FormsService_ListDocument_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListDocumentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FormsServiceServer).ListDocument(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.FormsService/ListDocument",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FormsServiceServer).ListDocument(ctx, req.(*ListDocumentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FormsService_Subscribe_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SubscribeRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(FormsServiceServer).Subscribe(m, &formsServiceSubscribeServer{stream})
}

type FormsService_SubscribeServer interface {
	Send(*SubscribeResponse) error
	grpc.ServerStream
}

type formsServiceSubscribeServer struct {
	grpc.ServerStream
}

func (x *formsServiceSubscribeServer) Send(m *SubscribeResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _FormsService_GetDocument_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDocumentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FormsServiceServer).GetDocument(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.FormsService/GetDocument",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FormsServiceServer).GetDocument(ctx, req.(*GetDocumentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FormsService_Listen_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ListenRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(FormsServiceServer).Listen(m, &formsServiceListenServer{stream})
}

type FormsService_ListenServer interface {
	Send(*ListenResponse) error
	grpc.ServerStream
}

type formsServiceListenServer struct {
	grpc.ServerStream
}

func (x *formsServiceListenServer) Send(m *ListenResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _FormsService_StopDocument_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopDocumentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FormsServiceServer).StopDocument(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.FormsService/StopDocument",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FormsServiceServer).StopDocument(ctx, req.(*StopDocumentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// FormsService_ServiceDesc is the grpc.ServiceDesc for FormsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FormsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "v1.FormsService",
	HandlerType: (*FormsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StartFromPreviousDocument",
			Handler:    _FormsService_StartFromPreviousDocument_Handler,
		},
		{
			MethodName: "StartDocument",
			Handler:    _FormsService_StartDocument_Handler,
		},
		{
			MethodName: "ListDocument",
			Handler:    _FormsService_ListDocument_Handler,
		},
		{
			MethodName: "GetDocument",
			Handler:    _FormsService_GetDocument_Handler,
		},
		{
			MethodName: "StopDocument",
			Handler:    _FormsService_StopDocument_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StartLocalDocument",
			Handler:       _FormsService_StartLocalDocument_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "Subscribe",
			Handler:       _FormsService_Subscribe_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "Listen",
			Handler:       _FormsService_Listen_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "forms.proto",
}
